# Description: net_http/internal/testing

package(default_visibility = ["//visibility:private"])

licenses(["notice"])

cc_binary(
    name = "net_logging_example",
    srcs = ["net_logging_example.cc"],
    deps = [
        "//net_http/internal:net_logging",
    ],
)
